Repository cloudfoundry/docs-dev-guide, pull requests merged in 2018-08, with the labels that each got.

#274 update language around service discovery for GA
  deploy-apps/cf-networking.html.md.erb
  deploy-apps/routes-domains.html.md.erb
Labels: unscheduled

#254 Add Multiple Buildpacks Verbage to Manifest Doc
  deploy-apps/manifest.html.md.erb
Labels: unscheduled

#262 Add V3 Command HTTP Invocation Text For App Health
  deploy-apps/healthchecks.html.md.erb
Labels: unscheduled

#271 Update CF Events: Crashed Event With Diego Cell & Instance Guid
  deploy-apps/troubleshoot-app-health.html.md.erb
Labels: unscheduled

#272 Remove V3-APP From List of Experimental
  v3-commands.html.md.erb
Labels: unscheduled

#275 Remove obsolete NFS mount warnings
  services/_using-vol-services.html.md.erb
Labels: scheduled

#276 Add NFS Volume Service docs
  services/_using-vol-services.html.md.erb
Labels: in progress

#277 Document nfs-experimental service performance improvements
  services/_using-vol-services.html.md.erb
Labels: unscheduled

#269 Service instance sharing is now GA
  services/sharing-instances.html.md.erb
Labels: unscheduled

#278 Clarify references to nfs-experimental as a separate service, not a plan
  services/_using-vol-services.html.md.erb
Labels: unscheduled
