Repository cloudfoundry/docs-dev-guide, pull requests merged in 2018-06, with the labels that each got.

#259 Add documentation for internal routes
  deploy-apps/routes-domains.html.md.erb
Labels: in progress

#261 Add Note that a Dash is a Forbidden Character in Manifests
  deploy-apps/manifest.html.md.erb
Labels: unscheduled

#265 add new v3 commands
  v3-commands.html.md.erb
Labels: scheduled
