Repository cloudfoundry/docs-dev-guide, pull requests merged in 2018-05, with the labels that each got.

#246 update docs to reflect instance identity OU update with org/space guid
  deploy-apps/instance-identity.html.md.erb
Labels: scheduled

#248 add ldap bind-service example
  services/using-vol-services.html.md.erb
Labels: scheduled

#250 Edit instance identity usage document
  deploy-apps/instance-identity.html.md.erb
Labels: in progress

#256 Add SSH proxy security configuration details
  deploy-apps/ssh-apps.html.md.erb
Labels: scheduled

#252 Add Variable Substitution Feature to Manifest Doc [#157270890]
  deploy-apps/manifest.html.md.erb
Labels: unscheduled

#257 Fixes Manifest Output Display
  deploy-apps/manifest.html.md.erb
Labels: unscheduled

#258 Improve Example for Partial Values
  deploy-apps/manifest.html.md.erb
Labels: unscheduled
