Repository cloudfoundry/docs-dev-guide, pull requests merged in 2019-04, with the labels that each got.

#340 blue-green deploys as a usecase
  weighted-routing.html.md.erb
Labels: in progress

#341 Change app to applies
  deploy-apps/cf-scale.html.md.erb
Labels: scheduled

#344 Disable networking
  deploy-apps/cf-networking.html.md.erb
Labels: unscheduled

#343 Add note clarifying environment variable rules
  deploy-apps/manifest-attributes.html.md.erb
Labels: scheduled
